# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_masreml_wrappers", use_symbols = TRUE, package_name = "masreml")

#' @usage NULL
#' @useDynLib masreml, .registration = TRUE
NULL

#' Build SNP additive G matrix (VanRaden)
r_build_g_snp_add <- function(w) .Call(wrap__r_build_g_snp_add, w)

#' Build SNP dominance D matrix (Da et al. 2014)
r_build_g_snp_dom <- function(w) .Call(wrap__r_build_g_snp_dom, w)

#' Build MH additive Agh matrix (Da 2015)
r_build_g_mh_add <- function(hap1, hap2, n_alleles) .Call(wrap__r_build_g_mh_add, hap1, hap2, n_alleles)

#' Build pedigree A matrix (Henderson)
r_build_a_ped <- function(sire, dam, n) .Call(wrap__r_build_a_ped, sire, dam, n)

#' Run adaptive REML (HE -> AI-REML -> EM-REML fallback)
r_run_reml <- function(y, x, g_list, method, max_iter, tol, n_threads) .Call(wrap__r_run_reml, y, x, g_list, method, max_iter, tol, n_threads)

#' Solve EBV — auto-selects Cholesky (n < 10k) or PCG (n >= 10k)
r_solve_ebv <- function(y, x, g_list, sigma2, solver, max_iter, tol) .Call(wrap__r_solve_ebv, y, x, g_list, sigma2, solver, max_iter, tol)

#' Pre-compute Cholesky factorization of V for reuse in IRLS
#' Returns external pointer to FactorizedV
#' @export
r_factorize_v <- function(g_list, sigma2, n) .Call(wrap__r_factorize_v, g_list, sigma2, n)

#' Solve BLUP using pre-factorized V — no re-factorization
#' @export
r_solve_with_factor <- function(factor, y, x, g_list, sigma2) .Call(wrap__r_solve_with_factor, factor, y, x, g_list, sigma2)


# nolint end
