#' @keywords internal
"_PACKAGE"

.onLoad <- function(libname, pkgname) {
  # extendr handles Rust library loading automatically
  # via src/entrypoint.c generated by rextendr::use_extendr()

  # Set default options
  op <- options()
  op_masreml <- list(
    masreml.threads  = parallel::detectCores(logical = FALSE),
    masreml.tol      = 1e-8,
    masreml.max_iter = 100L,
    masreml.verbose  = TRUE
  )
  toset <- !(names(op_masreml) %in% names(op))
  if (any(toset)) options(op_masreml[toset])

  invisible()
}

.onAttach <- function(libname, pkgname) {
  ver <- utils::packageVersion("masreml")
  packageStartupMessage(sprintf(
    "masreml %s — Universal REML-BLUP for SNP and Microhaplotype Genomic Prediction",
    ver
  ))
}

.onUnload <- function(libpath) {
  library.dynam.unload("masreml", libpath)
}